# Continuous Integration Workflow
name: "CI Build"

on:
  pull_request:
    branches:
      - master
  workflow_call:

env:
  RGBDS_VERSION: "v0.9.0"

jobs:
  build-ubuntu:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      # SET ENVIRONMENT VARIABLES
      - id: set-env-var
        name: "Set environment variables"
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      # INSTALL DEPENDENCIES
      - id: apt-get-depends
        name: "Install build dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install bison gcc git make -y;

      # CHECKOUT RGBDS
      - id: checkout-rgbds
        name: "Checkout gbdev/rgbds"
        uses: actions/checkout@v4
        with:
          path: rgbds
          ref: ${{ env.RGBDS_VERSION }}
          repository: gbdev/rgbds

      # INSTALL RGBDS
      - id: install-rgbds
        name: "Install gbdev/rgbds"
        working-directory: rgbds
        run: |
          sudo make install

      # CHECKOUT REPOSITORY
      - id: checkout-polishedcrystal
        name: "Checkout Rangi42/polishedcrystal"
        uses: actions/checkout@v4

      # BUILD ROMS
      - id: build-polishedcrystal
        name: "Build polishedcrystal"
        run: |
          make -j$(nproc)
          mkdir build
          mv polishedcrystal-3.0.0.gbc build/polishedcrystal-3.0.0-${{ env.SHORT_SHA }}.gbc
          mv polishedcrystal-3.0.0.sym build/polishedcrystal-3.0.0-${{ env.SHORT_SHA }}.sym
          make tidy

      - id: build-polishedcrystal-faithful
        name: "Build polishedcrystal-faithful"
        run: |
          make -j$(nproc) faithful
          mv polishedcrystal-3.0.0.gbc build/polishedcrystal-faithful-3.0.0-${{ env.SHORT_SHA }}.gbc
          mv polishedcrystal-3.0.0.sym build/polishedcrystal-faithful-3.0.0-${{ env.SHORT_SHA }}.sym
          make tidy

      # BUILD VC PATCHES
      - id: build-polishedcrystal-vc
        name: "Build polishedcrystal vc"
        run: |
          make -j$(nproc) vc
          mkdir build
          mv polishedcrystal-3.0.0.gbc build/polishedcrystal-3.0.0-${{ env.SHORT_SHA }}-vc.gbc
          mv polishedcrystal-3.0.0.patch build/polishedcrystal-3.0.0-${{ env.SHORT_SHA }}.patch
          mv polishedcrystal-3.0.0.sym build/polishedcrystal-3.0.0-${{ env.SHORT_SHA }}-vc.sym
          make tidy

      - id: build-polishedcrystal-faithful-vc
        name: "Build polishedcrystal-faithful vc"
        run: |
          make -j$(nproc) faithful vc
          mv polishedcrystal-3.0.0.gbc build/polishedcrystal-faithful-3.0.0-${{ env.SHORT_SHA }}-vc.gbc
          mv polishedcrystal-3.0.0.patch build/polishedcrystal-faithful-3.0.0-${{ env.SHORT_SHA }}.patch
          mv polishedcrystal-3.0.0.sym build/polishedcrystal-faithful-3.0.0-${{ env.SHORT_SHA }}-vc.sym
          make tidy

      # BUILD DEBUG ROMS
      - id: build-polisheddebug
        name: "Build polisheddebug"
        run: |
          make -j$(nproc) debug vc
          mv polishedcrystal-3.0.0.gbc build/polisheddebug-3.0.0-${{ env.SHORT_SHA }}.gbc
          mv polishedcrystal-3.0.0.sym build/polisheddebug-3.0.0-${{ env.SHORT_SHA }}.sym
          make tidy

      - id: build-polisheddebug-faithful
        name: "Build polisheddebug-faithful"
        run: |
          make -j$(nproc) faithful debug vc
          mv polishedcrystal-3.0.0.gbc build/polisheddebug-faithful-3.0.0-${{ env.SHORT_SHA }}.gbc
          mv polishedcrystal-3.0.0.sym build/polisheddebug-faithful-3.0.0-${{ env.SHORT_SHA }}.sym
          make tidy

      - id: build-polisheddebug-vc
        name: "Build polisheddebug vc"
        run: |
          make -j$(nproc) debug vc
          mv polishedcrystal-3.0.0.gbc build/polisheddebug-3.0.0-${{ env.SHORT_SHA }}-vc.gbc
          mv polishedcrystal-3.0.0.patch build/polisheddebug-3.0.0-${{ env.SHORT_SHA }}.patch
          mv polishedcrystal-3.0.0.sym build/polisheddebug-3.0.0-${{ env.SHORT_SHA }}-vc.sym
          make tidy

      - id: build-polisheddebug-faithful-vc
        name: "Build polisheddebug-faithful vc"
        run: |
          make -j$(nproc) faithful debug vc
          mv polishedcrystal-3.0.0.gbc build/polisheddebug-faithful-3.0.0-${{ env.SHORT_SHA }}-vc.gbc
          mv polishedcrystal-3.0.0.patch build/polisheddebug-faithful-3.0.0-${{ env.SHORT_SHA }}.patch
          mv polishedcrystal-3.0.0.sym build/polisheddebug-faithful-3.0.0-${{ env.SHORT_SHA }}-vc.sym
          make tidy

      # UPLOAD ARTIFACTS – only if the repo is owned by Rangi42 (i.e., not a fork)
      - id: upload-polishedcrystal
        if: ${{ github.repository_owner == 'Rangi42' }}
        name: "Upload polishedcrystal artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: "polishedcrystal"
          retention-days: 1
          path: |
            build/polishedcrystal-3.0.0-${{ env.SHORT_SHA }}.*

      - id: upload-polishedcrystal-faithful
        if: ${{ github.repository_owner == 'Rangi42' }}
        name: "Upload polishedcrystal-faithful artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: "polishedcrystal-faithful"
          retention-days: 1
          path: |
            build/polishedcrystal-faithful-3.0.0-${{ env.SHORT_SHA }}.*

      - id: upload-polisheddebug
        if: ${{ github.repository_owner == 'Rangi42' }}
        name: "Upload polisheddebug artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: "polisheddebug"
          retention-days: 1
          path: |
            build/polisheddebug-3.0.0-${{ env.SHORT_SHA }}.*

      - id: upload-polisheddebug-faithful
        if: ${{ github.repository_owner == 'Rangi42' }}
        name: "Upload polisheddebug-faithful artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: "polisheddebug-faithful"
          retention-days: 1
          path: |
            build/polisheddebug-faithful-3.0.0-${{ env.SHORT_SHA }}.*
